name: PySDMachine

env: 
  PYTHON: "" 
      
defaults:
  run:
    shell: bash
    working-directory: .

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]  # TODO: macos-latest
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1.6.0
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          cd test/Atmos/Parameterizations/Microphysics/KM_PySDMachine
          julia --project -e 'using Pkg; Pkg.add(url="../../../../../../ClimateMachine.jl")'
      - run: |
          cd test/Atmos/Parameterizations/Microphysics/KM_PySDMachine
          julia --project -e 'using Pkg; Pkg.resolve;'
      - run: |
          julia -e 'using Pkg; Pkg.add("Conda.jl")'
          julia -e 'using Conda; Conda.pip_interop(true); Conda.pip("install", "PySDM==1.12")'
      - run: |
          cd test/Atmos/Parameterizations/Microphysics/KM_PySDMachine
          julia --project runtests.jl
          
